### PR TITLE
Add Gateway

### PR DESCRIPTION
**Pull request by ty4tw**

### CODE REVIEW

**Comment by icraggs** [comment]
Hi Tomoaki.    You have to sign an Eclipse CLA for me to be able to accept your contribution (see https://www.eclipse.org/legal/clafaq.php)

Also, I'd prefer this to go to a branch other than master, either develop, or one specific to the gateway.  Thanks!

**Comment by ralight** [comment]
With >8000 lines of contribution this needs to go through proper IP review I believe, we can't just accept it even if the CLA is signed.

**Comment by icraggs** [comment]
Good point Roger.  Is the lines of code limit 2500 these days?  I'll open a CQ

**Comment by ralight** [comment]
I thought it was 1000 lines, but either way 8000 lines is definitely over the limit.

**Comment by ty4tw** [comment]
Hi All,
I  signed up CLA.
How can I make a pull request as a new branch like develop or gateway?

**Comment by ty4tw** [comment]
Can some one prepare a new branch as gateway ?
I will fork it and make a pull request again.

**Comment by icraggs** [comment]
Tomoaki:

I've added a "gateway" branch.  When you create the pull request, I'll need to kick off a separate IP check process with Eclipse legal.  This will take a while, but I will be able to work from your pull request.

You've signed the CLA, which is great.  But you also have to sign off your pull request too.

**Comment by ty4tw** [comment]
Thanks.

I did it  and finally succeeded.

I developed this from scratch and using nothing special liberally.
I P check will not take a time hopefully.


2016-05-13 6:12 GMT+09:00 Ian Craggs <notifications@github.com>:

**Pull request closed without merging**
