### PR TITLE
Gateway - Add UDP6 sensor network

### PR DESCRIPTION
**Pull request by benjaminaigner**
Due to the requirements (IPv6 only) of a RFC7668 network (6lowpan over Bluetooth Low Energy),
I've added a new sensor network to the gateway, which is UDPv6 based.

Works well in combination with ESP32 as sensor node, connected to HomeAssistant with an embedded MQTT Broker.

### CODE REVIEW

**Comment by ty4tw** [comment]
Thank you for your great contribution.  
Eclipse requires to follow https://wiki.eclipse.org/Development_Resources/Handling_Git_Contributions  for IP protections.  please check it. 

And  add 
script: 
  - cd MQTTSNGateway 
  - make CXX="g++-4.8" SENSORNET="xbee"
  - make CXX="g++-4.8" SENSORNET="udp"
  - make CXX="g++-4.8" SENSORNET="udp6"  <==== this line 
  - make test

to . travis.yml file.

any one can change the config file for their use. 
but,  do not change 
BrokerName=iot.eclipse.org
for - make test.
 
Sorry, I did not mention about those in comments. 

thank you for your contribution again.

**Comment by benjaminaigner** [comment]
So, I changed everything, signed that, but still your ip-validation fails...

Please advise :-)

**Comment by benjaminaigner** [comment]
Hi,

ok, I think I've killed github :-).
I've created a patch of all my commits, including the signed-off-by messages.

[udp6_patch.patch.txt](https://github.com/eclipse/paho.mqtt-sn.embedded-c/files/1038213/udp6_patch.patch.txt)

**Comment by ty4tw** [comment]
Thank you

you need some more process for significant contribution.
http://www.eclipse.org/legal/ECA.php
eclipse foundation prepare a LDAP account for you.
Then your sign-off is authorized by LDAP.

**Comment by ty4tw** [comment]
Hi Benjamin,

Could you get ECA ?

**Comment by benjaminaigner** [comment]
Hi,

I have a green tick at my Eclipse account status for the ECA.
I've added my Github account, maybe this was misssing (different account name, but same email address).

What do you think is wrong?

Sry for this mess :-)

**Comment by ty4tw** [comment]
Hi,

I have a same experience when I was first-time contributor.      
I'm not sure what is wrong, but in my case I did follows: 

1) Close Pull request.    
2) Change some portion and commit.    
3) Add commit comment with    
        **Signed-off-by: your_name <your_id@your_domain>**      
        System use this comment and the mail address you registered to Eclipse for authorization. 
4) Create New Pull request again.    

As step 2, adding 4 new parameter's explanations into README.md is good for us.    
 ex)  GatewayUDP6Port, GatewayUDPIf.....

**Comment by ty4tw** [comment]
Hi,

Reason of this error might be a different account name.
According to the Error detail, (click Details)

Current status

The pull request did not pass Eclipse validation.

The following users do not have valid ECAs. Please see this page for details, or to sign a ECA.
noreply@github.com

The following users have invalid Signed-off-by footers. Please use the Signed-Off-By (git commit -s) mechanism to confirm the origin of the submission. The identity in the Signed-off-By must match the Author or the Committer.
**benjaminaigner**

The following users have invalid Signed-off-by footers. Please use the Signed-Off-By (git commit -s) mechanism to confirm the origin of the submission. The identity in the Signed-off-By must match the Author or the Committer.
noreply@github.com

**Comment by ty4tw** [comment]
Hi,

when I click a Detail of ip-validation, Error messages are shown as follows:
Current status

The pull request did not pass Eclipse validation.

The following users do not have valid ECAs. Please see this page for details, or to sign a ECA.
noreply@github.com

The following users have invalid Signed-off-by footers. Please use the Signed-Off-By (git commit -s) mechanism to confirm the origin of the submission. The identity in the Signed-off-By must match the Author or the Committer.
**benjaminaigner**

The following users have invalid Signed-off-by footers. Please use the Signed-Off-By (git commit -s) mechanism to confirm the origin of the submission. The identity in the Signed-off-By must match the Author or the Committer.
noreply@github.com

The reason of your error might be your name.

**Comment by benjaminaigner** [comment]
Ok, I will close this and try again :-)

**Pull request closed without merging**
