### PR TITLE
Gateway improvements

### PR DESCRIPTION
**Pull request by suchomar**
Hi,
Here are some improvements for MQTTGateway.  I hope you will find them useful.

### CODE REVIEW

**Comment by icraggs** [comment]
Hi. Can you give a short description of what your changes do?  Are there tests that could/should be added?

**Comment by suchomar** [comment]
[Don't use object after it was deleted.](https://github.com/eclipse/paho.mqtt-sn.embedded-c/pull/103/commits/16e498c523c1137e09c9bf70dae0f1ee789aa168) - `ClientList::erase` method deletes client object. Invoking `Client::getNextClient` method on deleted object is dangerous. Fix: store pointer to next client in list before deleting object.

[Lock critical section when adding new Client to list](https://github.com/eclipse/paho.mqtt-sn.embedded-c/pull/103/commits/1507269d68495e8d6d12326a6dc592fdfe485590) - added missing mutex.lock to match existing mutex.unlock and to assure synchronized access to client list.

[Fix adding elements to WaitREGACKPacketList](https://github.com/eclipse/paho.mqtt-sn.embedded-c/pull/103/commits/9bd811c0b1c23d26db5abaf24e8e4202c3ccaad6) - adding first packet to WaitREGACKPacketList was broken because elm->_next was set to this elm and created loop which could result in crash at ~WaitREGACKPacketList()

[Fix gateway crash when subscribing to short topics (two octets length)](https://github.com/eclipse/paho.mqtt-sn.embedded-c/pull/103/commits/2e9abb8fbb79aa9f0784f41a5cb003434ae66b7d) - In MQTTSNSubscribeHandler::handleSubscribe topic was NULL for the case when
`topicFilter.type == MQTTSN_TOPIC_TYPE_SHORT`
and this resulted in crash at
` client->setWaitedSubTopicId(msgId, topic->getTopicId(), topicFilter.type);`
Fix: topicId variable was created with correct value for all cases.

[Fix unsubscribing from short topics (two octets length)](https://github.com/eclipse/paho.mqtt-sn.embedded-c/pull/103/commits/aaa563639886eaa475017b89c76c139115a69501) - in MQTTSNSubscribeHandler::handleUnsubscribe for the case when
`topicFilter.type == MQTTSN_TOPIC_TYPE_SHORT`
variable shadowing occurs for `MQTTGWPacket* unsubscribe` and inner variable was modified instead of outer. As a result wrong packet was used at `ev1->setBrokerSendEvent` Fix: remove shadowing variable.

[Preventing memory leaks](https://github.com/eclipse/paho.mqtt-sn.embedded-c/pull/103/commits/7ed7a0662c9209d5178e89f8a2d6ea3260e52d45) - improving memory management.

[Fix topic name registration procedure started by GW when handling PUBLISH message](https://github.com/eclipse/paho.mqtt-sn.embedded-c/pull/103/commits/d6b8a60f5e42e805ddb66f619466fbe66658337c) - in MQTTGWPublishHandler::handlePublish `MQTTSNString topicName` was initialized without setting cstring field to NULL as a result in `MQTTSNSerialize_register` cstring field was used instead of lenstring.

[Fix handling PUBREC message received from client](https://github.com/eclipse/paho.mqtt-sn.embedded-c/pull/103/commits/a38b78e60812e74a32e07e53ecb59451e4b127dc) - in PacketHandleTask::run there was missing `case MQTTSN_PUBREC` in switch statement and because of this PUBREC message was not handled.

**Comment by icraggs** [comment]
Thanks very much.  It looks good.  The requirements seem to be met.  If @tytw doesn't assess soon, I will :-)

**Comment by ty4tw** [comment]
Hi Ian,
Sorry for the late response.  my concern is copy right issue.
According to the eclipse pull request rule, contributor is required contributors agreement in case of more than 200 lines without copy right notice. This pull request is less than 200 lines but copy right notice is included. I'm not sure but avoid the regal problem later, suchomar should submit the eclipse contributor agreement. And clearly mention the copy right portion in the source code.
How do you think?

**Comment by icraggs** [comment]
Ah, thanks Tomoaki.  The usual approach I take is described here:

https://www.eclipse.org/projects/handbook/#ip-copyright-headers

/********************************************************************************
 * Copyright (c) {date} {owner}[ and others] 1
 *
 * This program and the accompanying materials are made available under the 2
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0 3
 *
 * Contributors: 4
 *   {name} - initial API and implementation
 ********************************************************************************/

_The {owner} is the name of the copyright holder. If the content is subsequently modified and appended to by other copyright owners, the words "and others" are typically appended. So for example: "XYZ Corp." or "XYZ Corp. and others". The words "and others" are used to avoid having to list every copyright owner and because often, most of the content in the file was contributed by the initial copyright owner with subsequent modifications by others being smaller._

The contributor section is where all the contributors can be listed.  

Does that help?

**Comment by suchomar** [comment]
Thank you for comments. Does this look legit now?

**Comment by ty4tw** [comment]
Hi, suchomar 
Thank you for your contribution.
I have reviewed your pull request.  some of commits need to be changed.

**Comment by suchomar** [comment]
Hi,
Thank you for review.
> Delete Copyright and add your name and company name to the Contributors section.

This is unclear to me. I changed this in [Fix Copyright headers](https://github.com/eclipse/paho.mqtt-sn.embedded-c/pull/103/commits/e77da0caf10b0c95bde0569105bb4e9fe93acb9f) commit
Are you requesting for changing Copyright and Contributors sections in each individual commit?

> Authorize required Client instances are created from the client list file before connection for authorization. 
And in this case, the instances are not erased.

So you mean that in `BrokerRecvTask::run`  we should move to next client only for authorized client?
```
/* delete client when the client is not authorized & session is clean */
_gateway->getClientList()->erase(client);

if ( client )
{
	client = client->getNextClient();
}
```
Unauthorized client is deleted and pointer to client **should be** set to NULL in `void ClientList::erase(Client* client)`? In that case reference to pointer to client should be passed like `void ClientList::erase(Client*& client)`

**Comment by ty4tw** [comment]
> In that case reference to pointer to client should be passed like void ClientList::erase(Client*& client)
yes that's the point. and also, set it 0 in the erase function.

Copyright notice in 5 files, 

MQTTSNGWBrokerRecvTask.cpp
MQTTSNGWClient.cpp
MQTTSNGWSubscribeHandler.cpp
MQTTGWPublishHandler.cpp
MQTTSNGWPacketHandleTask.cpp

should be changed as follows:

/**************************************************************************************
 * Copyright (c) 2016, Tomoaki Yamaguchi
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * and Eclipse Distribution License v1.0 which accompany this distribution.
 *
 * The Eclipse Public License is available at
 *    http://www.eclipse.org/legal/epl-v10.html
 * and the Eclipse Distribution License is available at
 *   http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * Contributors:
 *    Tomoaki Yamaguchi - initial API and implementation and/or initial documentation
 *    suchomar          - Gateway improvements
 **************************************************************************************/

**Comment by suchomar** [comment]
Hi,
Concerning the copyright notice
> suchomar - Gateway improvements

as all my work is done on behalf of Tieto Poland Sp. z o.o. I guess it would be appropriate to change it to

`Tieto Poland Sp. z o.o. - Gateway improvements`

**Comment by ty4tw** [comment]
Hi, 
Tieto Poland Sp. s o.o  is fine and Thank you for you contribution.

MQTTSNClient.h and MQTTSNClient.cpp  should be changed for the bug of ClientList::erase(Client* client).  Could you change the code for this?  or Marge once then I will change it.  which do you prefer?

**Comment by suchomar** [comment]
Hi,
I can change also ClientList::erase together with Copyright changes.

**Comment by ty4tw** [comment]
Thanks.  I'm waiting your update.

**Comment by suchomar** [comment]
Done. Please review.

**Comment by ty4tw** [comment]
All commits  disappeared.   
I can't see any commit.
May be, you did force-push.
Please, close this PR and create new PR.
Sorry for the inconvenience.

**Comment by ty4tw** [comment]
Hi, suchomar 
Thank you for your Contributions.

**Comment by suchomar** [comment]
Hi,
I am glad I was able to help.

**Pull request merged**
