### PR TITLE
install the gateway system-wide

### PR DESCRIPTION
**Pull request by andreas-ibm**
I wanted to be able to build and run this from a system-wide environment without needing to know the location of the git clone. 
So I updated the Makefile to take a prefix and install the components there...

### CODE REVIEW

**Comment by ty4tw** [comment]
Thank you for your contribution.
cmake should be a final solution for this issue.
I have no skill to do it. can I ask a favor of you?

**Comment by andreas-ibm** [comment]
yeah, I'm not a huge cmake person either, I've used just about every *other* make system!

If I have time I'll take a look.  Although I don't think this gateway is a viable option for me anymore, only just noticed issue #34 !

Do you know of any server that supports qos -1?

**Comment by S3ler** [comment]
I can write a cmake file for the MQTTSNGateway and update the README.md

But then:
 * the current MQTTSNGateway's Makefile is gone (will be generated by cmake) 
 * the install target will be system-wide (e.g. /usr/local/bin on Debian)

Is that ok?

Another thing are the the *.conf files which are copied next to the git clone location.
This makes no sense when we install it system-wide.
What shall I do with the configuration files?

After installing it system-wide we should think about a systemd unit file so we can manage via `sudo service mqttsngateway start | stop | status` .

**Comment by ty4tw** [comment]
Hi S3Ier,
Thank  you for your proposal.
I noticed it that updating a Makefle is enough because of your proposal.  
If some one wants to install programs into specific directory, command line is as follows:
````
$ make install INSTALL_DIR=/any/pah/you/like CONFIG_DIR=/any/pah/you/like
````
I will change the Makefile.

**Pull request closed without merging**
