### PR TITLE
Gateway - Add UDP6 sensor network v2

### PR DESCRIPTION
**Pull request by benjaminaigner**
Ok, this is a reopen for #60 , with additional documentation.

### CODE REVIEW

**Comment by benjaminaigner** [comment]
The current error is since I added my github account ID to my Eclipse account:

The identity in the Signed-off-By must match the Author or the Committer.

    benjaminaigner

My signed-off-by footer equals my eMail from GitHub & Eclipse, the name too.
But I can't get it, why there is noreply@github.com as contributor??

**Comment by ty4tw** [comment]
Hi, All

Does any one knows how to solve this ip-validation problem?

**Comment by ty4tw** [comment]
Hi benjamin,

could you check your Eclispe account?

1. go https://www.eclipse.org/legal/ecafaq.php
2. click 10. How do I sign a ECA?
3. click **Eclipse projects**    
4. Login your Eclipse account

Does  your Email Address and Legal Name equal signed-off-by footer ?
 if not chang them and click **REVOKE**

**Comment by benjaminaigner** [comment]
Did I miss anything?
According to these screenshots, it should be alright:
screenshot from 2017-06-08 08-29-19
screenshot from 2017-06-08 08-29-32
screenshot from 2017-06-08 08-29-57
screenshot from 2017-06-08 08-30-30

**Comment by ty4tw** [comment]
Hi,
Nothing is wrong.

try to delete **, added signe-off-by** from your commit message    0716766  .
because, 	325aea1 is OK. the big difference is **signe-off-by** part.

Current commit message is as follows:
```
changed broker name to pass travis,  added signe-off-by
Signed-off-by: Benjamin Aigner <aignerb@technikum-wien.at>    
```
shold be
```
changed broker name to pass travis
Signed-off-by: Benjamin Aigner <aignerb@technikum-wien.at>    
```
I'm not sure but cut & try something to solve this problem.
Thank you for your cooperation.

**Comment by icraggs** [comment]
I don't specifically know what is wrong - I'm usually on the other end of PRs rather than making them myself!

So the email address that the Eclipse ECA check recognizes is aignerb@technikum-wien.at.  Is that email address also associated with your Github id?  When I go to Tomoaki's Github profile, I see his email address, when I go to Benjamin's, I don't see it.

If we can't solve this ourselves, then we can ask for help from the Eclipse webmaster, who created and manage this process, by raising a bug at bugs.eclipse.org with the appropriate product/component tags.

**Comment by benjaminaigner** [comment]
@icraggs I tried to change my profile to have a public eMail (was disabled), maybe it solves this issue?

@ty4tw I intentionally missed out that "d", to avoid confusing any text parsing :-)

**Comment by ty4tw** [comment]
Hi benjamin,
    
      
1. I knew your intention.
but  325aea1    
````   
Added additional copyright note
Signed-off-by: Benjamin Aigner <aignerb@technikum-wien.at>
````   
**passed the validation check.   so I thought, erase that part and try.**
　　　　
        
       
        
           
2. I can see your mail address.     
    
mail

**Comment by ty4tw** [comment]
Hi benjamin,
Same issue has been reported to Bugzilla seance last year  and not solved yet. 
https://bugs.eclipse.org/bugs/show_bug.cgi?id=498340

Your contributions passed the Eclipse IP validation process. 
This PR is a evidence of the validation. 

So, Plan B is needed.
I will
1) Close this PR.
2) Copy your udp6 directory and files to my Rep.
3) Create the New PR  from my Rep and merge it.

You will
4) make a clone again after merging for your future maintenance.

How do you think about this plan?
Shall we try ?

**Comment by benjaminaigner** [comment]
As discussed with @ty4tw , I will close this PR now. @ty4tw will merge my commits.

THX for all the help, sry for these problems.
Next time I will only use git cli, to avoid any errors.

**Comment by ty4tw** [comment]
Benjamin agreed to try plan B.

**Pull request closed without merging**
